Update Orb Best Practices Guidelines.md
CircleCI-Public/Orb-Policies pull request #12
Opened 2019-10-15 07:43 UTC by sakshamtaneja21

2019-10-17 20:10 UTC, KyleTryon approved these changes
There are some legitimate corrections in here that needed to be addressed. We will accept this PR thank you!

2019-10-17 20:11 UTC, KyleTryon requested changes

2019-10-17 20:11 UTC, KyleTryon commented on Orb Best Practices Guidelines.md
> +            *   Patch: Minor bug fixes, metadata updates, or other safety actions.
Safe was correct here

2019-10-29 22:44 UTC, sakshamtaneja21 commented on Orb Best Practices Guidelines.md
> +            *   Patch: Minor bug fixes, metadata updates, or other safety actions.
sure 
will change

2019-10-29 22:45 UTC, sakshamtaneja21 commented on Orb Best Practices Guidelines.md
> +            *   Patch: Minor bug fixes, metadata updates, or other safety actions.
done

2019-11-04 20:45 UTC, KyleTryon commented
We appreciate your additions and apologize but this document has been migrated. This can be edited here if you wish to still submit changes. Sorry for the inconvenience. 
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/orbs-best-practices.md

2019-11-04 20:45 UTC, closed without merging